"""Initial migration

Revision ID: 77529a9f5f40
Revises: 
Create Date: 2026-06-30 11:04:53.133448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '77529a9f5f40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_linea', sa.String(length=20), nullable=False),
    sa.Column('color_linea', sa.String(length=7), nullable=False),
    sa.Column('imagen_microbus', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_linea')
    )
    op.create_index(op.f('ix_lineas_id'), 'lineas', ['id'], unique=False)
    op.create_table('puntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=True),
    sa.Column('stop', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ## op.create_index('idx_puntos_geometria', 'puntos', ['geometria'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_puntos_id'), 'puntos', ['id'], unique=False)
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ruta', sa.String(length=20), nullable=False),
    sa.Column('distancia_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_total_minutos', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['linea_id'], ['lineas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_id'), 'rutas', ['id'], unique=False)
    op.create_table('linea_ruta_puntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('distancia_acumulada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_acumulado', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['punto_id'], ['puntos.id'], ),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linea_ruta_puntos_id'), 'linea_ruta_puntos', ['id'], unique=False)
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.Integer(), nullable=False),
    sa.Column('ruta_origen_id', sa.Integer(), nullable=False),
    sa.Column('ruta_destino_id', sa.Integer(), nullable=False),
    sa.Column('penalizacion_minutos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['punto_id'], ['puntos.id'], ),
    sa.ForeignKeyConstraint(['ruta_destino_id'], ['rutas.id'], ),
    sa.ForeignKeyConstraint(['ruta_origen_id'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_id'), 'transferencias', ['id'], unique=False)
    ## op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ## op.create_table('spatial_ref_sys',
    ## sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    ## sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    ## sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    ## sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    ## sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    ## sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    ## sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    ## )
    op.drop_index(op.f('ix_transferencias_id'), table_name='transferencias')
    op.drop_table('transferencias')
    op.drop_index(op.f('ix_linea_ruta_puntos_id'), table_name='linea_ruta_puntos')
    op.drop_table('linea_ruta_puntos')
    op.drop_index(op.f('ix_rutas_id'), table_name='rutas')
    op.drop_table('rutas')
    op.drop_index(op.f('ix_puntos_id'), table_name='puntos')
    ## op.drop_index('idx_puntos_geometria', table_name='puntos', postgresql_using='gist')
    op.drop_table('puntos')
    op.drop_index(op.f('ix_lineas_id'), table_name='lineas')
    op.drop_table('lineas')
    # ### end Alembic commands ###